version: '3.8'

services:
  app:
    container_name: olvan-back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6363:6363"
    environment:
      - TZ=Asia/Tashkent
volumes:
  pgdata:
