version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: olvanuser
      POSTGRES_PASSWORD: 'olvanpassword#'
      POSTGRES_DB: olvanbackdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U olvanuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/olvanbackdb
      SPRING_DATASOURCE_USERNAME: olvanuser
      SPRING_DATASOURCE_PASSWORD: 'olvanpassword#'
    ports:
      - "6363:6363"

volumes:
  pgdata:
