spring:
  application:
    name: olvan-back
  datasource:
    url: jdbc:postgresql://localhost:5432/olvanbackdb
    username: postgres
    password: 1313
  jpa:
    hibernate:
      ddl-auto: none # don't touch, it gonna be disaster if you change!
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master-local.xml
    default-schema: public
    drop-first: false # again don't touch, I've already warned you above!
    clear-checksums: true
    contexts: olvan
server:
  port: 6363
env:
  url:
    name: http://192.168.214.40:6363
    description: "Local Server"
logging:
  level:
    org.hibernate.orm.connections.pooling: warn
jwt:
  secret: OlvanProjectAboutEducation134567890098765434567898765DFGHJKRTYUIcvbnmghjkuytttyuioqwertyuiolkkjgfdszxcvbnm
  expiry: 604800000 #milliseconds = 7 days