spring:
  application:
    name: olvan-back
  datasource:
    url: jdbc:postgresql://188.245.193.2:5432/olvanbackdb
    username: olvanuser
    password: "olvanpassword#"
  jpa:
    hibernate:
      ddl-auto: none # don't touch, it gonna be disaster if you change!
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master-local.xml
    default-schema: public
    drop-first: false # again don't touch, I've already warned you above!
    clear-checksums: true
    contexts: olvan
server:
  port: 6363
env:
  url:
    name: http://188.245.193.2:6363
    description: "Prod Server"
logging:
  level:
    org.hibernate.orm.connections.pooling: warn
jwt:
  secret: OlvanProjectAboutEducation134567890098765434567898765DFGHJKRTYUIcvbnmghjkuytttyuioqwertyuiolkkjgfdszxcvbnm
  expiry: 604800000 #milliseconds = 7 days
minio:
  url: http://188.245.193.2:9000
  bucket: olvan-bucket
  username: minioadmin
  password: minioadmin123