CREATE TABLE if not exists olvan_students (
                                id bigint generated by default as identity primary key,
                                full_name TEXT,
                                parents_full_name TEXT,
                                student_phone_number VARCHAR(255),
                                parents_phone_number VARCHAR(255),
                                enroll_type VARCHAR(255),
                                date_begin DATE,
                                attendance INT,
                                course_type TEXT,
                                teacher_name TEXT,
                                user_id BIGINT NOT NULL UNIQUE,
                                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                FOREIGN KEY (user_id) REFERENCES olvan_users(id)
);

CREATE TABLE if not exists student_organization (
                                      student_id BIGINT NOT NULL,
                                      organization_id BIGINT NOT NULL,
                                      PRIMARY KEY (student_id, organization_id),
                                      FOREIGN KEY (student_id) REFERENCES olvan_students(id),
                                      FOREIGN KEY (organization_id) REFERENCES olvan_organizations(id)
);

