CREATE TABLE if not exists student_organization_lesson (
                                             id bigint generated by default as identity primary key,
                                             student_id BIGINT,
                                             organization_id BIGINT,
                                             lesson_id BIGINT,
                                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                             CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES olvan_students(id),
                                             CONSTRAINT fk_organization FOREIGN KEY (organization_id) REFERENCES olvan_organizations(id),
                                             CONSTRAINT fk_lesson FOREIGN KEY (lesson_id) REFERENCES olvan_lessons(id)
);
