CREATE TABLE if not exists olvan_organizations (
                                     id bigint generated by default as identity primary key,
                                     full_name TEXT,
                                     phone_number VARCHAR(255),
                                     director_phone_number VARCHAR(255),
                                     director_full_name VARCHAR(500),
                                     date_begin DATE,
                                     address TEXT,
                                     inn_or_pinfl VARCHAR(255),
                                     user_id BIGINT NOT NULL UNIQUE,
                                     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                     FOREIGN KEY (user_id) REFERENCES olvan_users(id)
);
