CREATE TABLE if not exists olvan_contracts (
                                    id bigint generated by default as identity primary key,
                                    file_name VARCHAR(500) NOT NULL,
                                    file_path VARCHAR(500) NOT NULL,
                                    file_size BIGINT NOT NULL,
                                    file_created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    user_id BIGINT UNIQUE,
                                    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES olvan_users(id)
);
