CREATE TABLE if not exists users (
                       id bigint generated by default as identity primary key,
                       username VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       role VARCHAR(255) NOT NULL,
                       is_active BOOLEAN NOT NULL
);
