CREATE TABLE if not exists olvan_teachers (
                                id bigint generated by default as identity primary key,
                                full_name TEXT,
                                degree VARCHAR(255),
                                phone_number VARCHAR(255),
                                gender VARCHAR(255),
                                email VARCHAR(255),
                                date_begin DATE,
                                experience DECIMAL(10, 2),
                                student_count INT,
                                course_type TEXT,
                                user_id BIGINT NOT NULL UNIQUE,
                                org_id BIGINT,
                                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                FOREIGN KEY (user_id) REFERENCES olvan_users(id)
);
