CREATE TABLE if not exists olvan_contracts (
                                 id bigint generated by default as identity primary key,
                                 file_name VARCHAR(500) NOT NULL,
                                 file_path VARCHAR(500) NOT NULL,
                                 file_size BIGINT NOT NULL,
                                 org_id BIGINT,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
