CREATE TABLE if not exists olvan_clients (
                               id bigint generated by default as identity primary key,
                               full_name TEXT,
                               phone_number VARCHAR(255),
                               address TEXT,
                               enroll_type VARCHAR(255),
                               bio TEXT,
                               user_id BIGINT UNIQUE,
                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               CONSTRAINT fk_client_user FOREIGN KEY (user_id) REFERENCES olvan_users(id)
);
