create table if not exists olvan_subscriptions(
                      id bigint generated by default as identity primary key,
                      enroll_type varchar(500),
                      definition TEXT,
                      amount bigint
)